---
all:
  vars:
    ansible_connection: ssh
    ansible_user: D003446
    ansible_become: true
    ansible_ssh_private_key_file: /data/sshkey
    jolokia_enabled: false
    #repository_configuration: custom
    #custom_yum_repofile_filepath: db-rpm-yzdh-dih.repo

zookeeper:
  hosts:
    ya4533.danskenet.net:
    ya4534.danskenet.net:
    ya4535.danskenet.net:

kafka_broker:
  hosts:
    ya4533.danskenet.net:
    ya4534.danskenet.net:
    ya4535.danskenet.net:

schema_registry:
  hosts:
    ya4533.danskenet.net:
    ya4534.danskenet.net:
    ya4535.danskenet.net:

control_center:
  hosts:
    ya4533.danskenet.net:
