---
all:
  vars:
    ansible_connection: ssh
    ansible_user: D003446
    ansible_become: true
    ansible_ssh_private_key_file: /data/sshkey
    jolokia_enabled: false

zookeeper:
  hosts:
    ya4533.local.net:
    ya4534.local.net:
    ya4535.local.net:

kafka_broker:
  hosts:
    ya4533.local.net:
    ya4534.local.net:
    ya4535.local.net:

schema_registry:
  hosts:
    ya4533.local.net:
    ya4534.local.net:
    ya4535.local.net:

control_center:
  hosts:
    ya4533.local.net:
